# Generated by Django 5.1.6 on 2025-02-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relationship_app", "0003_book_alter_userprofile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Librarian", "Librarian"),
                    ("Member", "Member"),
                ],
                max_length=20,
            ),
        ),
    ]
