# Generated by Django 5.1.6 on 2025-02-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relationship_app", "0002_remove_book_author_remove_library_books_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("published_date", models.DateField()),
            ],
            options={
                "permissions": [
                    ("can_add_book", "Can add a book"),
                    ("can_change_book", "Can edit a book"),
                    ("can_delete_book", "Can delete a book"),
                ],
            },
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Librarian", "Librarian"),
                    ("Member", "Member"),
                ],
                max_length=10,
            ),
        ),
    ]
